config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models

  resources :messages
  root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :find_message, only: [:show, :edit, :update, :destroy]
    
    def index
        @messages = Message.all.order("created_at DESC")
    end
    
    def show
       
    end
    
    def new
        @message = current_user.messages.build
    end
    
    def create
        @message = current_user.messages.build(message_params)
        if @message.save
            redirect_to root_path
        else
            render 'new'
        end
    end
    
    def edit
        
    end
    
    def update
        if @message.update(message_params)
        redirect_to message_path
        else
        render 'edit'
        end
    end
    
    def destroy
        @message.destroy
        redirect_to root_path
    end
    
    private
    
        def message_params
            params.require(:message).permit(:title, :description)
        end
        
        def find_message
            @message = Message.find(params[:id]) 
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Board</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    
        <div class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <%= link_to "Message Board", root_path, class: "navbar-brand" %>
                </div>
                <ul class="nav navbar-nav">
                    <li><%= link_to "Sign up", new_user_registration_path %></li>
                    <% if user_signed_in? %>
                    <li><%= link_to "Sign out", destroy_user_session_path, method: :delete  %></li>
                    <% else %>
                    <li><%= link_to "Log in",  new_user_session_path %> </li>
                    <% end %>
                </ul>
                <% if user_signed_in? %>
                    <p><%= link_to "New Message", new_message_path, class: "navbar-right navbar-text navbar-link" %></p>
                <% else %> 
                
                <% end %>
            </div>
        </div>

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       
<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %>
    <h2><%= message.title %></h2>
    <%= link_to "View Message", message_path(message), class: "btn btn-default" %>
<% end %>

<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>
<h2><%= @message.description %></h2>
<!-- Add a posted at timestamp -->

<%= link_to "Back", root_path %>
<%= link_to "Edit", edit_message_path(@message) %>
<%= link_to "Delete", message_path(@message), method: :delete, data: { confirm: "Are you sure?" } %>